networks:
  digital_net:
    name: digital_net
    driver: bridge

volumes:
  digital-volume:
    driver: local

services:
  database:
    image: postgres:13
    container_name: digital_game
    volumes:
      - digital-volume:/var/lib/postgresql/data
    ports:
      - "5454:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=game
    networks:
      - digital_net